### ISSUE TITLE
Output additional statistics about ref, alt, and ambiguous reads

### ISSUE THREAD

**Issue by jzook** [svviz/svviz#11]
It would be great to output statistics like the mean and standard deviation of alignment scores, number of snps, and number of indels in reads aligned to ref, alt, or ambiguously. For ambiguous reads, it would probably be best to exclude read pairs that map completely on one side of the event or the other. I expect these stats will be useful understanding whether the sv has accurate breakpoints.

**Comment by nspies** [comment]
split this into a separate issue: #12; and bd928547e2f0bc101bcd16b66cdd76e4d6edb2aa closes the additional summary statistics issue
