### ISSUE TITLE
svviz crashes after not being able to find reads for certain SV events

### ISSUE THREAD

**Issue by rpadmanabhan** [svviz/svviz#17]
So I am running svviz in the batch mode and inputting a vcf file. The problem is it crashes midway and throws me an error like : 
Couldn't find reads on chromosome 'scaffold_203'; trying instead 'chrscaffold_203'
Traceback (most recent call last):
  File "/usr/local/bin/svviz", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 296, in main
    run(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 257, in run
    readCount = loadReads(dataHub)
  File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 75, in loadReads
    sample.searchDistance, sample.singleEnded, dataHub.args.include_supplementary)
  File "/usr/local/lib/python2.7/site-packages/svviz/remap.py", line 180, in getReads
    raise e
ValueError: start out of range (-176)

I checked the bam file and there are indeed reads present for the region. This happens for a few of the SV events. These SVs are inversions.

**Comment by nspies** [comment]
This occurred because there were genomic coordinates near the beginning of the scaffold chromosome, which became negative when svviz tried to expand the region. I've pushed a fix to the debug17 branch -- could you check that it fixes your issue? You can install the branch something like this:

`sudo pip install -U git+git://github.com/svviz/svviz.git@debug17`

Since I don't have any structural variants near chromosome ends, if you could do a sanity check to make sure the output looks reasonable, that would be appreciated.

**Comment by rpadmanabhan** [comment]
Thanks, I will do that and let you know how it goes.

**Comment by rpadmanabhan** [comment]
That seems to have fixed the issue, I will run it across all the samples I have and let you know if something looks wierd.

**Comment by rpadmanabhan** [comment]
Hi, So when I was running the batch, I encountered a problem with one of the inversion events and the program crashed. 

The error I get : 
- Running for variant 603/604 Inversion::scaffold_2878:446-1,074 *
- Loading reads and finding mates *
  - AC_bowtie
    Traceback (most recent call last):
    File "/usr/local/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.3.3.dev0', 'console_scripts', 'svviz')()
    File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 330, in main
    run(sys.argv)
    File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 285, in run
    readCount, readLength = loadReads(dataHub)
    File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 85, in loadReads
    sample.searchDistance, sample.singleEnded, dataHub.args.include_supplementary)
    File "/usr/local/lib/python2.7/site-packages/svviz/remap.py", line 200, in getReads
    searchRegions = variant.searchRegions(searchDistance)
    File "/usr/local/lib/python2.7/site-packages/svviz/variants.py", line 341, in searchRegions
    return [Locus(chrom, self.region.start()-searchDistance, self.region.end()+searchDistance, "+")]
    File "/usr/local/lib/python2.7/site-packages/svviz/utilities.py", line 99, in **init**
    raise Exception("Locus start coordinate cannot be negative: {}".format(start))
    Exception: Locus start coordinate cannot be negative: -63

**Comment by nspies** [comment]
Ooops, missed one event type (sorry, looks like it _almost_ finished running!). Can you update your code again from that branch and try again?

On Oct 27, 2015, at 10:41 AM, Raghavendra Padmanabhan <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, So when I was running the batch, I encountered a problem with one of the inversion events and the program crashed.

The error I get :
-   Running for variant 603/604 Inversion::scaffold_2878:446-1,074 *
-   Loading reads and finding mates *
  -   AC_bowtie Traceback (most recent call last): File "/usr/local/bin/svviz", line 9, in load_entry_point('svviz==1.3.3.dev0', 'console_scripts', 'svviz')() File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 330, in main run(sys.argv) File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 285, in run readCount, readLength = loadReads(dataHub) File "/usr/local/lib/python2.7/site-packages/svviz/app.py", line 85, in loadReads sample.searchDistance, sample.singleEnded, dataHub.args.include_supplementary) File "/usr/local/lib/python2.7/site-packages/svviz/remap.py", line 200, in getReads searchRegions = variant.searchRegions(searchDistance) File "/usr/local/lib/python2.7/site-packages/svviz/variants.py", line 341, in searchRegions return [Locus(chrom, self.region.start()-searchDistance, self.region.end()+searchDistance, "+")] File "/usr/local/lib/python2.7/site-packages/svviz/utilities.py", line 99, in init raise Exception("Locus start coordinate cannot be negative: {}".format(start)) Exception: Locus start coordinate cannot be negative: -63

**Comment by rpadmanabhan** [comment]
so just have to do sudo pip install -U git+git://github.com/svviz/svviz.git@debug17 again to update it ?

**Comment by nspies** [comment]
yes

On Oct 27, 2015, at 10:53 AM, Raghavendra Padmanabhan <notifications@github.com<mailto:notifications@github.com>> wrote:

so just have to do sudo pip install -U git+git://github.com/svviz/svviz.git@debug17 again to update it ?

**Comment by nspies** [comment]
Just wanted to check if this seems to be working now for you.

**Comment by rpadmanabhan** [comment]
I don't know for some reason the genotyping was taking a very long time ( I waited about 12 hrs or so) and only half of the SVs were done. So I am just messing around with the MAPQ thresholds to make it faster. Strangely, for the same sample the whole process was almost done in 2 hrs earlier.

**Comment by nspies** [comment]
Okay, let me know either way!

**Comment by nspies** [comment]
I'm going to close this -- please reopen or create a new issue if you're still having problems
