### ISSUE TITLE
how to specify the strandness when visualize translocations 

### ISSUE THREAD

**Issue by crazyhottommy** [svviz/svviz#28]
I saw in the documentation:

```
Translocations:     
Translocations can be specified using the following format: `chrom1 start1 chrom2 start2 orientation`,   where orientation is either + or -, and specifies whether region1 and region2 are both on the plus   strand of the genome, or are on opposite genomic strands.
```

Could you please explain a bit how the orientation is specified?

Say I have a translocation in bedpe format:

```
chr1 3000 3050  chr7 5000 5050  name  quality  +  +
```

does that mean `chr1 3000 3050 +` is in the plus strand and `chr7 5000 5050 +`  is in the plus strand as well and I need to specify the orientation `+` when using svviz?

I am a bit confused..

Thanks!
Ming

**Comment by nspies** [comment]
I believe your interpretation is correct, although there is limited documentation on how structural variants are supposed to be represented in bedpe file format. I've added a bit more detail on translocations and breakends to the documentation [here](http://svviz.readthedocs.org/en/latest/commandline.html#translocations-and-breakends).

The upshot is that breakend mode is probably more similar conceptually to the bedpe format, although a translocation could be visualized with either breakend or translocation mode. Please let me know if you're still confused.

**Comment by nspies** [comment]
PS also note that the translocation event type shows two reciprocal events simultaneously, which is why there are only 2 possible orientations.

**Comment by crazyhottommy** [comment]
Thanks for your reply. I am using [svtools](https://github.com/hall-lab/svtools) to convert vcf4.2 output by [lumpy](https://github.com/arq5x/lumpy-sv) to bedpe.

when I look at the vcf ouput for one sv, check the `strands=-+`.
BND as in the [vcf4.2](http://samtools.github.io/hts-specs/VCFv4.2.pdf) specification. 

```
14      38454918        5956_2  N       ]8:9174263]N    25.35   .       SVTYPE=BND;STRANDS=-+:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0
8       9174263 5956_1  N       N[14:38454918[  25.35   .       SVTYPE=BND;STRANDS=+-:4;CIPOS=-9,8;CIEND=-9,8;CIPOS95=0,0;CIEND95=0,0;MATEID=....
```

when it is converted to bedpe:

```
8   9174253 9174271 14  38454908    38454926    my_sv   25.35  +   -  BND  ....
```

I noticed that the strands is  `+ -` for this particular example when converted to bedpe.

Now, compare it to the vcf4.2 specification:

```
REF ALT Meaning
s t[p[ piece extending to the right of p is joined after t
s t]p] reverse comp piece extending left of p is joined after t
s ]p]t piece extending to the left of p is joined before t
s [p[t reverse comp piece extending right of p is joined before t


The example in Figure 1 shows a 3-break operation involving 6 breakends. It exemplifies all possible orientations
of breakends in adjacencies. Notice how the ALT field expresses the orientation of the breakends.
#CHROM POS ID REF ALT QUAL FILTER INFO
2 321681 bnd W G G]17:198982] 6 PASS SVTYPE=BND
2 321682 bnd V T ]13:123456]T 6 PASS SVTYPE=BND
13 123456 bnd U C C[2:321682[ 6 PASS SVTYPE=BND
13 123457 bnd X A [17:198983[A 6 PASS SVTYPE=BND
17 198982 bnd Y A A]2:321681] 6 PASS SVTYPE=BND
17 198983 bnd Z C [13:123457[C 6 PASS SVTYPE=BND
```

and  look at the figure in the specification:

<img width="470" alt="screenshot 2015-12-02 14 28 10" src="https://cloud.githubusercontent.com/assets/4106146/11543213/05a0cdb0-9901-11e5-8467-d78b301a3e54.png">

My particular example will be similar to breakpoint `U` ( with strand +) and `V` (with strand -)

Do you think I am correct?

Thanks!
Ming

**Comment by nspies** [comment]
Hi Ming,

The strands attribute is not a standard VCF attribute, but it appears to have the following definition from lumpy:

`
##INFO=<ID=STRANDS,Number=.,Type=String,Description="Strand orientation of the adjacency in BEDPE format (DEL:+-, DUP:-+, INV:++/--)">
`

from which I infer that it's referring to the orientation of the reads supporting the event, rather than the genomic sequence itself.

The vcf 4.2 spec seems to be pretty clear, and I think your original interpretation of this event as a "+" type translocation (for purposes of running svviz) is correct.

(If there are reads that support this event in your bam, you should be able to figure this out by trying both orientations out - only one of which should be supported by the reads.)

**Comment by crazyhottommy** [comment]
Thanks for your answer, also see the same question and answer on the `lumpy` lab github page https://github.com/hall-lab/svtools/issues/5#issuecomment-161432757

**Comment by crazyhottommy** [comment]
Look at the figure, if my breakpoints are `W` and `Y` , I should specify `-` when use svviz?
the same for `X` and `Z`

Thanks!

**Comment by nspies** [comment]
Yes!
