### ISSUE TITLE
Help message should include all event types

### ISSUE THREAD

**Issue by nh13** [svviz/svviz#36]
Event types (`-t`) include: `del`, `ldel`, `ins`, `mei`, `tra`, and `bkend`.  See: https://github.com/svviz/svviz/blob/master/src/svviz/variants.py#L56-L73

**Comment by nspies** [comment]
I'm a little confused, as all the event types appear to be in the help message. I've updated the message to include the abbreviations (eg `ldel` for `largedeletion`) -- is that what you meant? See 6ee37d9d0a4600b7fc69e26be66f219663a70fe4

**Comment by nh13** [comment]
I am using svviz version 1.4.0.

<img width="949" alt="screen shot 2016-01-26 at 12 56 10 pm" src="https://cloud.githubusercontent.com/assets/846274/12589542/40e6f7cc-c42c-11e5-8e53-ce427641a889.png">

I only see a few event types.  I installed svviz with pip.

**Comment by nspies** [comment]
great, got it, fixed by a09b019580e12f6db0428404daed2fa8b34a2695

**Comment by nh13** [comment]
Thanks @nspies .  This is great software, so fast responses are appreciated.
