### ISSUE TITLE
Orientation override and orientation for breakpoint spanning reads.

### ISSUE THREAD

**Issue by nh13** [svviz/svviz#37]
1. I would request that the `orientation` value can be overridden on the command line.
2. I think there is a bug when looking at reads that is a chromosomal translocation that joins a chromosome from the `+` strand and a chromosome from the `-` strand.  I have a read that _directly_ observes the breakpoint.  When I run `svviz` normally, the read is counted as ambiguous.  When I modify the source to allow for the `orientation` to be `any`, the read is counted as alternative.  My current hypothesis is that the read pairs should be `+/-` but look like `+/+` or `-/-`  I am not sure what is going on, but I thought I would try to report it.

**Comment by nspies** [comment]
1. Sure, I can make the orientation a command-line option (it used to be, before I implemented inferring it from the data).
2. Would you mind sending me the the command line you used to call svviz, as well as the full terminal output?

If you can also send me the data relevant to the event in question, that would also be helpful -- you can use the `--save-reads` option to create a bam with just the reads near the event and 50,000 reads from a random genomic region used to infer the orientation and insert size. You can send me the bam by email at nspies@stanford.edu (the file should be just a few megabytes).
