### ISSUE TITLE
Output stats as they're generated during batch mode?

### ISSUE THREAD

**Issue by jzook** [svviz/svviz#38]
Currently, when a batch mode process fails, it doesn't output any stats to the --summary output file, even for the sites that successfully completed.  Since it will occasionally fail for a variety of reasons, it would be great to output the stats to the summary file as it runs, so that we could restart where it stopped.

**Comment by nspies** [comment]
I'm a bit hesitant to do this for two reasons: first, this will only work if there's an exception in python (ie a bug in svviz) and not if python fully crashes (eg when the realignment code crashes); and second, if you're running this locally, and you already had a full summary file, it would overwrite that with an incomplete summary file.

How about a compromise: the summary to this point gets printed out to the terminal?

**Comment by jzook** [comment]
I see. That's definitely better than nothing, though it might be difficult
to use. Could you instead write it to a .tmp file with the same name before
the extension?

**Comment by nspies** [comment]
I'm closing this as it seems a better solution is to chunk the input file into smaller sub-jobs
