### ISSUE TITLE
more documentation.

### ISSUE THREAD

**Issue by zeeev** [svviz/svviz#40]
Installed svviz strait out the gate, props for that!  I'm excited to automate 100s of regions.

I'm having some trouble interpreting the plot.  Here are some pieces of information that would really help.
1. Are split reads colored?
2. Are soft-clips displayed? 
3. Are inverted and everted reads colored?

Here the output for a simulated duplication:
[test.pdf](https://github.com/svviz/svviz/files/230747/test.pdf)

**Comment by nspies** [comment]
Sure, happy to expand on these points. Let's start from here:

http://svviz.readthedocs.org/en/latest/visualizations.html#visual-output

I'm going to edit the final paragraph to more directly address your questions:

> The read alignments displayed in svviz are the result of a Smith-Waterman realignment of the full read sequence against the reference allele or the inferred alternate allele. Reads aligning to the minus strand are colored red and those aligning to the plus strand are colored purple. If the sample contains paired-end sequencing reads, the unsequenced space between read pairs is shown by light gray bars. **Only reads matching the expected orientation (typically inwards-facing for standard Illumina libraries) will be assigned to one of the alleles** (those aligning with unexpected orientations will be counted as ambiguous).
> 
> Overlapping portions of read pairs are shown in a light green color (for example, if the insert size is 250 and 2x150bp sequencing was performed, the middle 50bp would be sequenced from both reads). 
> 
> Mismatches to the sequence of the allele are shown as colored vertical bars with the width of a nucleotide (you may need to zoom in to see them). Insertions or deletions, relative to the sequence of the assigned allele, are displayed as gray and cyan bars, respectively. Sequencing errors will thus show up as isolated vertical bars within individual read sequences; polymorphisms (SNPs and indels) will show up as vertical bars spanning multiple reads at the same position.

Because we're just doing a Smith-Waterman realignment, there aren't split reads.

Soft-clips are not currently displayed but it would be pretty easy to add that in (do you have a favorite color?). If you want this, could you just open another issue and I'll try to get to it next week?

Does this make sense so far? Please let me know if that clears things up or if there are things that are still unclear.

**Comment by zeeev** [comment]
Noah,

Thank you for the clarification, it hit the spot.  I think I was looking for a forced alignment to the reference. In ~15-20% of deletions the SW fails to align the reads from the deleted allele to the alternate sequence. Often deletions have insertions at the breakpoint (spent a lot of time looking at this).  If you had a reference only mode and parsed the SW cigars you could annotate splits, inversions and everts.  The beauty of SVViz is you can run it without X11(we are working in the cloud). We'd love to use it to represent weird mapping patterns to the reference, rather than a slow, memory intensive program that can't handle batches. Something to think about... 

I'll open a soft clip ticket. Maybe a colorblind aware color?

**Comment by nspies** [comment]
Okay, I've pushed the edited docs f3d6d81b02285557d80fbb23cf4552b090777e98.

It sounds like you'd like to parse the realignments yourself. I think it should be relatively easy to dump those to a bam file for you to play with. Please feel free to file more tickets if you'd like help implementing new features.

**Comment by zeeev** [comment]
Noah,

I've written an SV caller that does that that (wham).  I'm looking for a visualization solution that is simple and isn't a full blown browser. We have a couple hundred genomes and we want to plot the regions of interest across the populations.
