### ISSUE TITLE
AssertionError in svviz

### ISSUE THREAD

**Issue by sandoro** [svviz/svviz#43]
I am trying to install svviz on a CentOS6 running python 2.7.12.
I installed svviz via "pip install svviz" into an Anaconda virtual environment.
This svviz depends on joblib/0.10.0 and "svviz demo" fails 
with the (closed) svviz issue #42  'module' object has no attribute 'SafeFunction' .

Via google I found a developer's discussion of this problem that recommended a fix which I applied
to "multiprocessor.py" starting at line 63 in the form 

```
    for i, chunk in enumerate(chunkIt(args, processes)):
####
#            result = pool.apply_async(joblib.parallel.SafeFunction(_map),
#                                                 [cls, methodname, initArgs, chunk, i, verbose])
####
          try:    # joblib <= 0.9.4
              from joblib.parallel import SafeFunction
          except ImportError:    # joblib >= 0.10.0
              from joblib._parallel_backends import SafeFunction
          result = pool.apply_async(SafeFunction(_map),
                                             [cls, methodname, initArgs, chunk, i, verbose])
```

This fixed the 'SafeFunction' problem.

On rerunning "svviz demo"  I had the error

>  .  .  .
>  Found 5,898 reads across 3 samples for a total of 531,714 nt
> - Realigning reads *
>   Traceback (most recent call last):
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/bin/svviz", 
>        line 11, in <module>  sys.exit(main())
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/svviz/app.py", 
>        line 350, in main   run(sys.argv)
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/svviz/app.py", 
>        line 319, in run   runRemap(dataHub)
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/svviz/app.py", 
>       line 116, in runRemap
>       sample.alnCollections = remap.do_realign(dataHub, sample)
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/svviz/remap.py", 
>       line 187, in do_realign
>       jobName=name.format("ref"))
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/svviz/remap.py", 
>       line 147, in do1remap
>       verbose=verbose, processes=processes, name=jobName))
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/site-packages/
>               svviz/multiprocessor.py", 
>       line 73, in map   [cls, methodname, initArgs, chunk, i, verbose])
>   File "/usr/local/Anaconda/envs_app/svviz/1.5.0/lib/python2.7/multiprocessing/pool.py", 
>       line 293, in apply_async
>       assert self._state == RUN
>   AssertionError

It seems likely that some process that is supposed to be running is not, in fact, running.
But the python Traceback does not help me to find the cause of that fact.

Is there a newer version of the svviz software that will remove this problem?
Any advice, suggestions, etc. will be greatly appreciated.

Thanks,

Sanford M. Orlow, PhD
Computer Engineer
National Institutes of Health 
CIT - HPC Group
12B 2N-207/E
12 South Dr. Bethesda, MD 20892-5680
PHONE  301-496-5362  EMAIL sandor@mail.nih.gov

**Comment by nspies** [comment]
Can you try `pip install -U svviz`? You're still running 1.5.1, which is the older (pre-fix) version of svviz.

**Comment by nspies** [comment]
Hi Sanford,

Can you please confirm that you've gotten this working?
- Noah

**Comment by sandoro** [comment]
Noah,

I did send you an email but I guess it was to the wrong address.

Yes, I  updated my svviz version (from v1.5.0 to v1.5.1) and this corrected the problem described in
Issue #43, "AssertionError in svviz".  Thanks, very much.

Subsequently, my testing of svviz uncovered another problem. Which I will submit as a new issue.

Sanford M. Orlow, PhD
Computer Engineer
National Institutes of Health
CIT - HPC Group
12B 2N-207/E
12 South Dr. Bethesda, MD 20892-5680
PHONE 301-496-5362 EMAIL sandor@mail.nih.gov

**Comment by nspies** [comment]
Okay, sounds good.
