### ISSUE TITLE
problems installing on Cygwin

### ISSUE THREAD

**Issue by pcantalupo** [svviz/svviz#46]
Hello,

I'm trying to install svviz on Cygwin and I'm getting the following error:
https://gist.github.com/pcantalupo/35a3b87e93786256916eba96887a9a08

I can't seem to figure out what to try next.  Thank you,
Paul

**Comment by nspies** [comment]
Hi Paul,

Hrm, I don't have much experience with Windows. It looks like you're hitting an error while trying to install pysam, which is a prerequisite of svviz. Can you try pip install pysam? The pysam developers might be able to help you figure out what's going on there (https://github.com/pysam-developers/pysam).

cheers,
Noah
