### ISSUE TITLE
svviz installation Ubuntu

### ISSUE THREAD

**Issue by mitul-patel** [svviz/svviz#48]
I have successfully installed svviz on ubuntu "pip install svviz"
But when I ran svviz from the command line it gives me error: "svviz: command not found"

I have no idea where it installed in ubuntu,

**Comment by nspies** [comment]
Can you “pip uninstall svviz” and then re-run “pip install svviz” and “svviz" and share the terminal output?

Alternatively, have you tried installing into a virtualenv? http://svviz.readthedocs.io/en/latest/install.html#venv


On May 25, 2017, at 3:19 AM, mitul-patel <notifications@github.com<mailto:notifications@github.com>> wrote:


I have successfully installed svviz on ubuntu "pip install svviz"
But when I ran svviz from the command line it gives me error: "svviz: command not found"

I have no idea where it installed in ubuntu,
