### ISSUE TITLE
svviz doesn't seem to honor `--processes`

### ISSUE THREAD

**Issue by ifiddes-10x-zz** [svviz/svviz#52]
When running `svviz` with `--processes` set to any number, in batch mode, I still see CPU usage spike up to the maximum present on the machine.

**Comment by nspies** [comment]
Hrm, I'm not able to replicate this -- it seems to use the expected number of processes when I set it to -1, 0, 1, or 4 in batch mode. Can you send more details, eg the command you're using to invoke svviz, which version (source or pypi), etc?

Also, version 2 of svviz is currently under development. If you want to give it a spin (still in alpha), you can find it at https://github.com/nspies/svviz2/

**Comment by ifiddes-10x-zz** [comment]
I am using version 1.6.2 from pypi. Example invocation is `svviz --type batch --summary summary.txt --processes 4 -b $bam $fasta $vcf`

I have attached both a log and a screenshot of top taken during the run that generated the log. From what I can tell, it seems to happen in the `* Assigning reads to most probable alleles *` step.

SVviz2 looks cool, but the requirement for python 3 is going to make things complicated for our cluster setup.

<img width="498" alt="screen shot 2018-01-23 at 9 26 54 am" src="https://user-images.githubusercontent.com/35242397/35290725-e618138a-001f-11e8-817d-da540c0aee4a.png">

[log.txt](https://github.com/svviz/svviz/files/1656995/log.txt)

**Comment by nspies** [comment]
I'm not quite sure what's going on here, as that step doesn't explicitly use multiple processes.

One potential hint is that your top monitor seems to indicate a single process using more than a single core at once, which python can't do on its own. This suggests that it's a C module being called from python -- depending on how it's installed, numpy can run multi-threaded, and this particular svviz step does use numpy a bit. The allele assignment step really shouldn't run for very long (your logs say typically 1-2s per variant) but if this is an issue for you, you could try checking if you have numpy setup with multicore support (see https://roman-kh.github.io/numpy-multicore/).

I know that python3 can sound like a problem in the abstract if everything you're running uses python2, but they were designed from day 1 to be installed side-by-side and it should be quite easy to get svviz2 running alongside your py2 code. To keep things more cleanly separated, I use virtualenvs but these aren't really necessary.

**Comment by ifiddes-10x-zz** [comment]
Good catch, it was numpy. Based on https://stackoverflow.com/questions/17053671/python-how-do-you-stop-numpy-from-multithreading I found that setting `export OMP_NUM_THREADS=1` resolved the issue.
