### ISSUE TITLE
Can variant-supporting reads be saved?

### ISSUE THREAD

**Issue by teng-gao** [svviz/svviz#54]
i.e. a bam of split reads and spanning reads

**Comment by nspies** [comment]
I don't believe the ``--save-reads`` option in svviz v1.x (this repository) will annotate reads as such. 

The output from [svviz2](https://github.com/nspies/svviz2) is divided into separate bams for ref and alt and the tags include some information relevant to this decision. svviz2 isn't quite as polished but the underlying functionality is much more deeply developed and I recommend using it instead if possible.
